[package]
name = "computations"
version = "0.1.0"
edition = "2024"

[features]
testutil = []

[dependencies]
tokio = { workspace = true }
futures = { workspace = true }
serde = { workspace = true }
postcard = { workspace = true }
blake3 = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
redb = { workspace = true }

[dev-dependencies]
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
tempfile = { workspace = true }
